//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionBank.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestionBank.Common.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Added Successfully. Would you like to add a new Record?.
        /// </summary>
        internal static string Message01 {
            get {
                return ResourceManager.GetString("Message01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated Successfully.
        /// </summary>
        internal static string Message02 {
            get {
                return ResourceManager.GetString("Message02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully.
        /// </summary>
        internal static string Message03 {
            get {
                return ResourceManager.GetString("Message03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Updated Sucessfully.
        /// </summary>
        internal static string Message04 {
            get {
                return ResourceManager.GetString("Message04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists.
        /// </summary>
        internal static string Message05 {
            get {
                return ResourceManager.GetString("Message05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added Successfully. Would you like to Assign a Role?.
        /// </summary>
        internal static string Message07 {
            get {
                return ResourceManager.GetString("Message07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Role Assigned to the User. Would you like Assign a Role?.
        /// </summary>
        internal static string Message08 {
            get {
                return ResourceManager.GetString("Message08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Added Sucessfully..
        /// </summary>
        internal static string Message09 {
            get {
                return ResourceManager.GetString("Message09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Add Record. Please Try Again.
        /// </summary>
        internal static string Message11 {
            get {
                return ResourceManager.GetString("Message11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update Record. Please Try Again.
        /// </summary>
        internal static string Message12 {
            get {
                return ResourceManager.GetString("Message12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete Record. Please Try Again.
        /// </summary>
        internal static string Message13 {
            get {
                return ResourceManager.GetString("Message13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update Status. Please Try Again.
        /// </summary>
        internal static string Message14 {
            get {
                return ResourceManager.GetString("Message14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred. Please Try Again.
        /// </summary>
        internal static string Message15 {
            get {
                return ResourceManager.GetString("Message15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred. Please Try Again.
        /// </summary>
        internal static string Message16 {
            get {
                return ResourceManager.GetString("Message16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Message25 {
            get {
                return ResourceManager.GetString("Message25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        internal static string Message26 {
            get {
                return ResourceManager.GetString("Message26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred. Please Try Again.
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred. Please Try Again.
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred. Please Try Again.
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred. Please Try Again.
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
    }
}
